### ISSUE TITLE
options issue (not even evaluated)

### ISSUE THREAD

**Issue by jflaflamme** [chmln/vue-wysiwyg#15]
First thanks for the plugin, look good.
However, I am not able to specify my upload URL (or any other options)

```
import Wysiwyg from "vue-wysiwyg";

Vue.use(Wysiwyg, {
  hideModules: { "bold": false },
  image: {
   uploadURL: "/my/upload",
   dropzoneOptions: {}
  }
})
```

I just tried building the trunk and got same error.
I am using vue-loader (so the component is called from a .vue file, maybe an emitter problem?)

Regards

**Comment by AraneaDev** [comment]
Can confirm, having the same issue when using vue-loader.

**Comment by jazibsawar** [comment]
is hideModules: { "bold": false } works for you?

**Comment by soundrussian** [comment]
Awesome plugin! The trouble with options is because for some reason the published code does not include changes from the last few commits where the bug with options was fixed.

Here's the diff: https://www.diffchecker.com/Q1p8RiuU. Left column is the published version, right column is a fresh build from master. As you can see, they differ, in the published version config is not overloaded (as it had been in version 1.2.5).

@chmln Is it possible that built process went wrong and version 1.2.6 was published with the old build?

**Comment by chmln** [comment]
@soundrussian Indeed looks like the build was outdated.
I've republished the updated build under `v1.2.7`
